# Generated by Django 5.2.7 on 2025-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения мест'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
